# Module: zeek
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.17/filebeat-module-zeek.html

- module: zeek
  capture_loss:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/capture_loss.log", "/opt/zeek/logs/*.capture_loss.json"]
  connection:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/conn.log", "/opt/zeek/logs/*.conn.json"]
  dce_rpc:
    enabled: false
  dhcp:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/dhcp.log", "/opt/zeek/logs/*.dhcp.json"]
  dnp3:
    enabled: false
  dns:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/dns.log", "/opt/zeek/logs/*.dns.json"]
  dpd:
    enabled: false
  files:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/files.log", "/opt/zeek/logs/*.files.json"]
  ftp:
    enabled: false
  http:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/http.log", "/opt/zeek/logs/*.http.json"]
  intel:
    enabled: false
  irc:
    enabled: false
  kerberos:
    enabled: false
  modbus:
    enabled: false
  mysql:
    enabled: false
  notice:
    enabled: false
  ntp:
    enabled: false
  ntlm:
    enabled: false
  ocsp:
    enabled: false
  pe:
    enabled: false
  radius:
    enabled: false
  rdp:
    enabled: false
  rfb:
    enabled: false
  signature:
    enabled: false
  sip:
    enabled: false
  smb_cmd:
    enabled: false
  smb_files:
    enabled: false
  smb_mapping:
    enabled: false
  smtp:
    enabled: false
  snmp:
    enabled: false
  socks:
    enabled: false
  ssh:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/ssh.log", "/opt/zeek/logs/*.ssh.json"]
  ssl:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/ssl.log", "/opt/zeek/logs/*.ssl.json"]
  stats:
    enabled: false
  syslog:
    enabled: false
  traceroute:
    enabled: false
  tunnel:
    enabled: false
  weird:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/weird.log", "/opt/zeek/logs/*.weird.json"]
  x509:
    enabled: true
    var.paths: ["/opt/zeek/logs/current/x509.log", "/opt/zeek/logs/*.x509.json"]

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
